#!/usr/bin/env bash
set -euo pipefail

export CLINICAL_SPEECH_RUNTIME_ROOT="${CLINICAL_SPEECH_RUNTIME_ROOT:-/data/project_runtime}"
export CLINICAL_SPEECH_DATASETS_DIR="${CLINICAL_SPEECH_DATASETS_DIR:-$CLINICAL_SPEECH_RUNTIME_ROOT/datasets}"
export CLINICAL_SPEECH_CHECKPOINTS_DIR="${CLINICAL_SPEECH_CHECKPOINTS_DIR:-$CLINICAL_SPEECH_RUNTIME_ROOT/checkpoints}"
export CLINICAL_SPEECH_LOGS_DIR="${CLINICAL_SPEECH_LOGS_DIR:-$CLINICAL_SPEECH_RUNTIME_ROOT/logs}"
export CLINICAL_SPEECH_CACHE_DIR="${CLINICAL_SPEECH_CACHE_DIR:-$CLINICAL_SPEECH_RUNTIME_ROOT/cache}"
export CLINICAL_SPEECH_HF_DIR="${CLINICAL_SPEECH_HF_DIR:-$CLINICAL_SPEECH_RUNTIME_ROOT/hf}"
export CLINICAL_SPEECH_TORCH_DIR="${CLINICAL_SPEECH_TORCH_DIR:-$CLINICAL_SPEECH_RUNTIME_ROOT/torch}"
export CLINICAL_SPEECH_PROFILER_DIR="${CLINICAL_SPEECH_PROFILER_DIR:-$CLINICAL_SPEECH_RUNTIME_ROOT/profiler}"
export CLINICAL_SPEECH_OUTPUTS_DIR="${CLINICAL_SPEECH_OUTPUTS_DIR:-$CLINICAL_SPEECH_RUNTIME_ROOT/outputs}"
export CLINICAL_SPEECH_TMP_DIR="${CLINICAL_SPEECH_TMP_DIR:-$CLINICAL_SPEECH_RUNTIME_ROOT/tmp}"
export CLINICAL_SPEECH_BENCHMARKS_DIR="${CLINICAL_SPEECH_BENCHMARKS_DIR:-$CLINICAL_SPEECH_RUNTIME_ROOT/benchmarks}"

export HF_HOME="${HF_HOME:-$CLINICAL_SPEECH_HF_DIR}"
export HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-$CLINICAL_SPEECH_HF_DIR/hub}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$CLINICAL_SPEECH_HF_DIR/transformers}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-$CLINICAL_SPEECH_HF_DIR/datasets}"
export TORCH_HOME="${TORCH_HOME:-$CLINICAL_SPEECH_TORCH_DIR}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$CLINICAL_SPEECH_CACHE_DIR/xdg}"
export TMPDIR="${TMPDIR:-$CLINICAL_SPEECH_TMP_DIR}"
export TMP="${TMP:-$TMPDIR}"
export TEMP="${TEMP:-$TMPDIR}"
export WANDB_DIR="${WANDB_DIR:-$CLINICAL_SPEECH_OUTPUTS_DIR/wandb}"
export WANDB_CACHE_DIR="${WANDB_CACHE_DIR:-$CLINICAL_SPEECH_CACHE_DIR/wandb}"
export WANDB_CONFIG_DIR="${WANDB_CONFIG_DIR:-$CLINICAL_SPEECH_CACHE_DIR/wandb-config}"
export PIP_CACHE_DIR="${PIP_CACHE_DIR:-$CLINICAL_SPEECH_CACHE_DIR/pip}"
export MPLCONFIGDIR="${MPLCONFIGDIR:-$CLINICAL_SPEECH_CACHE_DIR/matplotlib}"

mkdir -p \
  "$CLINICAL_SPEECH_RUNTIME_ROOT" \
  "$CLINICAL_SPEECH_DATASETS_DIR" \
  "$CLINICAL_SPEECH_CHECKPOINTS_DIR" \
  "$CLINICAL_SPEECH_LOGS_DIR" \
  "$CLINICAL_SPEECH_CACHE_DIR" \
  "$CLINICAL_SPEECH_HF_DIR" \
  "$CLINICAL_SPEECH_TORCH_DIR" \
  "$CLINICAL_SPEECH_PROFILER_DIR" \
  "$CLINICAL_SPEECH_OUTPUTS_DIR" \
  "$CLINICAL_SPEECH_TMP_DIR" \
  "$CLINICAL_SPEECH_BENCHMARKS_DIR" \
  "$HUGGINGFACE_HUB_CACHE" \
  "$TRANSFORMERS_CACHE" \
  "$HF_DATASETS_CACHE" \
  "$XDG_CACHE_HOME" \
  "$WANDB_DIR" \
  "$WANDB_CACHE_DIR" \
  "$WANDB_CONFIG_DIR" \
  "$PIP_CACHE_DIR" \
  "$MPLCONFIGDIR"

printf 'Storage environment configured under %s\n' "$CLINICAL_SPEECH_RUNTIME_ROOT"
printf 'Outputs:      %s\n' "$CLINICAL_SPEECH_OUTPUTS_DIR"
printf 'Logs:         %s\n' "$CLINICAL_SPEECH_LOGS_DIR"
printf 'Checkpoints:  %s\n' "$CLINICAL_SPEECH_CHECKPOINTS_DIR"
printf 'Caches:       %s\n' "$CLINICAL_SPEECH_CACHE_DIR"
printf 'Temporary:    %s\n' "$CLINICAL_SPEECH_TMP_DIR"
